name: Unit Tests and quality
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, created]
jobs:
  tests:
    name: Unit tests and quality
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Checkout
        uses: actions/checkout@v3 
      - name: Running tests
        run: make run/ci-test
      - name: Check Gofmt
        run: make run/check-gofmt
      - name: Make coverage file
        run: make coverage
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          prefix: github.com/gpbPiazza/docker-go-ci-cd
          coverageLocations: ${{github.workspace}}/.cover/*.out:gocov